services:
  mgnt-sw-yang:
    build:
      context: .
      dockerfile: Dockerfile
    image: mgnt-sw-yang-docker
    container_name: mgnt-sw-yang-docker
    ports:
      # ssh console
      - "2222:22"
      # Webssh console
      - "8888:80"
      #- "443:443"
    volumes:
      - data:/storage/
    restart: unless-stopped
    #network_mode: "host"

volumes:
  data: