services:
  clixon:
    build:
      context: .
      dockerfile: Dockerfile
    image: clixon-docker
    container_name: clixon-docker
    ports:
      # ssh console
      - "2222:22"
      # Webssh console
      - "8888:80"
      #- "443:443"
    volumes:
      - data:/storage/
    restart: unless-stopped

volumes:
  data: